name: soccer_quiz_flutter
description: Professional-ready Flutter client skeleton for Soccer Quiz.
publish_to: "none"
version: 0.2.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  test: ^1.21.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/profile.png

    